application: pixelcycle
version: draft
runtime: go
api_version: go1

handlers:

# cache front page assets
- url: /gif/6401356696911872
  static_files: front.gif
  upload: front.gif

- url: /json/6401356696911872
  static_files: front.json
  upload: front.json

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /
  script: _go_app

- url: /m[0-9]+
  script: _go_app

- url: /gif/[0-9]+
  script: _go_app

- url: /json/[0-9]+
  script: _go_app

- url: /save
  script: _go_app

- url: /(.*\.(css|js|js\.map|gif|dart))
  static_files: \1
  upload: (.*\.(css|js|js\.map|gif|dart))

- url: /(packages/.*/src/.*\.dart)
  static_files: \1
  upload: /packages/.*/src/.*\.dart

